using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace t2sBackend
{
    public enum PhoneCarrier
    {
        [Description("vtext.com")]
        Verizon,
        [Description("messaging.sprint.com")]
        Sprint,
        [Description("email.uscc.net")]
        USCellular,
        [Description("txt.att.com")]
        ATT,
        [Description("myboostmobile.com")]
        BoostMobile,
        [Description("comcastpcs.textmsg.com")]
        Comcast,
        [Description("qwestmp.com")]
        Qwest,
        [Description("tmomail.net")]
        TMobile,
        [Description("sms.wcc.net")]
        WestCentralWireless,
        [Description("pagemart.net")]
        WebLinkWireless,
        [Description("airmessage.net")]
        WebLinkWireless,
        [Description("voicestream.net")]
        VoiceStream,
        [Description("myvzw.com")]
        VerizonPCS,
        [Description("myairmail.com")]
        VerisonPagers,
        [Description("stpaging.com")]
        STPaging,
        [Description("email.skytel.com")]
        SkytelPagers,
        [Description("paging.acswireless.com")]
        SBCAmeritechPaging,
        [Description("ram-page.com")]
        RAMPage,
        [Description("pager.qualcomm.com")]
        Qualcomm,
        [Description("page.propage.net")]
        ProPage,
        [Description("email.uscc.net")]
        Primeco,
        [Description("mobilecell1se.com")]
        PriceCommunications,
        [Description("voicestream.net")]
        Powertel,
        [Description("pcsone.net")]
        PCSOne,
        [Description("page1nw.com")]
        PageOneNorthwest,
        [Description("pagegate.pagenet.ca")]
        PageNetCanada,
        [Description("pmcl.net")]
        PageMartCanada,
        [Description("pagemart.net")]
        PageMart,
        [Description("pacbellpcs.net")]
        PacificBell,
        [Description("omnipointpcs.com")]
        Omnipoint,
        [Description("page.nextel.com")]
        Nextel,
        [Description("isp.com")]
        Motient,
        [Description("beepone.net")]
        MorrisWireless,
        [Description("page.mobilcom.net")]
        MobilecomPA,
        [Description("page.metrocall.com")]
        Metrocall,
        [Description("pagemci.com")]
        MCI,
        [Description("inlandlink.com")]
        IndianaPagingCo,
        [Description("page.infopagesystems.com")]
        InfopageSystems,
        [Description("messagealert.com")]
        GTE,
        [Description("gte.pagegate.net")]
        GTE1,
        [Description("airmessage.net")]
        GTE2,
        [Description("epage.porta-phone.com")]
        GrayLinkPortaPhone,
        [Description("webpager.us")]
        GCSPaging,
        [Description("sendabeep.net")]
        GalaxyCorporation,
        [Description("page.hit.net")]
        DigiPagePageKansas,
        [Description("corrwireless.net")]
        CorrWirelessCommunications,
        [Description("cookmail.com")]
        CookPaging,
        [Description("pageme.comspeco.net")]
        CommunicationSpecialists,
        [Description("cingularme.com")]
        Cingular,
        [Description("cvcpaging.com")]
        CentralVermontCommunications,
        [Description("mycellone.com")]
        CellularOneWest,
        [Description("sbcemail.com")]
        CellularOne,
        [Description("cell1.textmsg.com")]
        CellularOne1,
        [Description("cellularone.textmsg.com")]
        CellularOne2,
        [Description("cellularone.txtmsg.com")]
        CellularOne3,
        [Description("swmsg.com")]
        CellularOneSouthWest,
        [Description("phone.cellone.net")]
        CellularOneEastCoast,
        [Description("blsdcs.net")]
        BellSouthMobility,
        [Description("bellsouthtips.com")]
        BellSouthBlackberry,
        [Description("wireless.bellsouth.com")]
        BellSouth,
        [Description("message.bam.com")]
        BellAtlantic,
        [Description("beepwear.net")]
        Beepwear,
        [Description("dpcs.mobile.att.net")]
        ATTPocketnetPCS,
        [Description("mobile.att.net")]
        ATTPCS,
        [Description("mmode.com")]
        ATTFree2Go,
        [Description("archwireless.net")]
        ArchPagersPageNet,
        [Description("clearpath.acswireless.com")]
        AmeritechClearpath,
        [Description("page.americanmessaging.net")]
        AmericanMessaging,
        [Description("paging.acswireless.com")]
        AmeritechPaging,
        [Description("alphanow.net")]
        AlphaNow,
        [Description("myairmail.com")]
        AirtouchPagers,
        [Description("advantagepaging.com")]
        AdvantageCommunications,
        [Description("cellularonewest.com")]
        WesternWireless,
        [Description("sms.wcc.net")]
        WestCentralWireless,
        [Description("vmobile.ca")]
        VirginMobileCanada,
        [Description("Virgin Mobile")]
        VirginMobile,
        [Description("uswestdatamail.com")]
        USWest,
        [Description("utext.com")]
        Unicel,
        [Description("tms.suncom.com")]
        Triton,
        [Description("msg.telus.com")]
        Telus,
        [Description("mobile.surewest.com")]
        SurewestCommunicaitons,
        [Description("tms.suncom.com")]
        Sumcom,
        [Description("txt.bell.ca")]
        SoloMobile,
        [Description("satellink.net")]
        Satellink,
        [Description("text.mtsmobility.com")]
        MTS,
        [Description("clearlydigital.com")]
        MidwestWireless,
        [Description("ivctext.com")]
        IllinoisValleyCellular,
        [Description("csouth1.com")]
        CellularSouth,
        [Description("bellmobility.ca")]
        BellCanada,
        [Description("txt.bellmobility.ca")]
        BellCanada2,
        [Description("message.alltel.com")]
        Alltel,
        [Description("paging.acswireless.com")]
        ACSWireless,
        [Description("sms.3rivers.net")]
        ThreeRiverWireless,
        [Description("blueskyfrog.com")]
        BlueSkyFrog,
       

    }
}
